# Generated by Django 3.1.1 on 2020-09-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20200907_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
